apiVersion: skaffold/v4beta3
kind: Config
manifests:
    rawYaml:
        - ./infra/k8s/*
build:
    local:
        push: false
    artifacts:
        - image: sachinprasad29/client
          context: client
          sync:
              manual:
                  - src: 'src/**/*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: sachinprasad29/comments
          context: comments
          sync:
              manual:
                  - src: '*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: sachinprasad29/event-bus
          context: event-bus
          sync:
              manual:
                  - src: '*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: sachinprasad29/moderation
          context: moderation
          sync:
              manual:
                  - src: '*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: sachinprasad29/posts
          context: posts
          sync:
              manual:
                  - src: '*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
        - image: sachinprasad29/query
          context: query
          sync:
              manual:
                  - src: '*.js'
                    dest: .
          docker:
              dockerfile: Dockerfile
